### ISSUE TITLE
Comparison with Textangular & CKeditor

### ISSUE THREAD

**Issue by yankustefan** [sachinchoolur/angular-trix#1]
Hey Sachin

This looks really great!
Still, I have to ask:

What are the pros and cons of this "module" compared to Textangular and/or CKeditor?

Or what was the main motivation behind making a new one?

Don't get me wrong, it really looks promising and I will try it out. Since I use Textangular & CKeditor. Just would love to hear the author's voice ;)

**Comment by talbotseb** [comment]
Same question here :+1:

**Comment by sachinchoolur** [comment]
Hi guys,

First of all i am not the author of trix editor. I just wrote an anguularjs directive for trix editor. You can have a look at the official [website](https://github.com/basecamp/trix) to know about more about trix editor.

Previously i was using textangular and i found some bugs then i felt it is not production ready. Started searching for some other WYSIWYG editors. Luckily i found trix which satisfies all my requirements.
But it was not angular based. So i wrote a directive wrapper for trix editor And it still supports all the features of trix editor.

**Comment by yankustefan** [comment]
Thank you for your feedback and to make this wrapper publicly available!
