### ISSUE TITLE
Nothing is initialize [SOLVED]

### ISSUE THREAD

**Issue by yoannpicquenot** [sachinchoolur/angular-trix#12]
Hello,

I'm want to use this impressive angular editor. So I installed angular-trix (with npm), included css and js files, and placed in my code, and finally loaded angularTrix module.

`<trix-editor angular-trix ng-model="article.text"></trix-editor>`

The problem is that I got this : 

![capture du 2016-05-18 00-03-29](https://cloud.githubusercontent.com/assets/6999772/15340863/fda456ea-1c8b-11e6-9218-06eeae04fd24.png)

Through the inspector I got this : 
`<trix-editor angular-trix="" ng-model="article.text" class="ng-pristine ng-untouched ng-valid ng-isolate-scope ng-not-empty"></trix-editor>`

Did I miss something to initialize ?

Thanks for considering my problem, and sorry for grammar mistakes if there are.

Yoann

**Comment by yaoyonstudio** [comment]
I got the same issue.

**Comment by yaoyonstudio** [comment]
just figure it out.
miss the main lib.

<script src="//cdnjs.cloudflare.com/ajax/libs/trix/0.9.2/trix.js"></script>

add this and it's doing fine.
