### ISSUE TITLE
Binding not working on popup

### ISSUE THREAD

**Issue by shamresh** [sachinchoolur/angular-trix#17]
I launch a modal (bootstrap) but the binding does not work.

If I put the binding in a div, I can see it is passed into modal however for the angular-trix component it does not appear.

My code is:

```
     $scope.editCommentDialog = function (comment) {
        var modalInstance = $modal.open({
            templateUrl: 'editCommentDialog.html',
            windowClass : 'edit-comment-modal-dialog',
            controller: function ($scope, $modalInstance, editedComment) {
                $scope.editedComment = editedComment;

                $scope.ok = function () {
                    $modalInstance.close(editedComment);
                };

                $scope.cancel = function () {
                    $modalInstance.dismiss('cancel');
                };
            },
            resolve: {
                editedComment: function () {
                   return { id : comment.id,  text : comment.text};
                }
            }
        });

        modalInstance.result.then(function (editedComment) {
            $scope.editedComment = editedComment;
            $scope.updateComment();
        }, function () {
            $log.info('Modal dismissed at: ' + new Date());
        });
    };
```

and

```
<script type="text/ng-template" id="editCommentDialog.html">
<div class="modal-header">
    <h3>Edit</h3>
</div>
<div class="modal-body">
    <trix-editor angular-trix ng-model="editedComment.text" class="trix-content editable-trix-editor"></trix-editor>
   </div>
   <div class="modal-footer">
    <button class="btn btn-primary" ng-click="ok()">OK</button>
    <button class="btn btn-warning" ng-click="cancel()">Cancel</button>
</div>
</script>
```

**Comment by spkn** [comment]
I have the exact same issue, I dont see the value specified in ng-model.

**Comment by shamresh** [comment]
I have seen others mention this issue on other groups. Please can we get this resolved, it is the only blocker I have before my app goes live.

**Comment by ablamunits** [comment]
I have experienced a similar issue (although not the exact same one). I was able to resolve it in my case by adding `ng-if="true"` to the `<trix-editor>` element. It might help in this scenario as well.

This repo seems dead.

**Comment by shamresh** [comment]
Thank you so much. That worked. Not sure how you found that solution but thanks once again.

**Comment by jinnabaalu** [comment]
ng-if="true" works perect

**Comment by ibnYusrat** [comment]
For me, ng-if="true" works only one way.. If I define a value in the controller for the model, it gets displayed in AngularTrix, but if I write something in trix, it doesn't update the model..

**Comment by sagar005pawar** [comment]
ng-if="true" works perect

**Comment by kboyd31** [comment]
Not sure why, but ng-if="true" worked perfectly for me too! Thank you!!! (if you're still around and can explain why that works I'd LOVE to know!)
