### ISSUE TITLE
Not showing model data when parent element has ng-if

### ISSUE THREAD

**Issue by goors** [sachinchoolur/angular-trix#22]
Like this:

```
<div data-ng-if="showTrix">
    <trix-editor angular-trix ng-model="someModel"></trix-editor>
</div>
```

"someModel" is not show as content at all. I tried adding ng-if="true" to trix-editor but no luck there!

Any idea?

**Comment by mpmadhuranga** [comment]
@goors have you tried without `data-ng-if="showTrix"`

**Comment by goors** [comment]
@madhurangaonbit I need with data-ng-if. But i fugured this out.

For some reason this is not working

<div data-ng-if="showExtra">
<div data-ng-if="showTrix[someModel]">
    <trix-editor angular-trix ng-model="someModel"></trix-editor>
</div>

</div>

When nested ng-if trix is not working.

**Comment by sureshkodur** [comment]
Why this is not working inside ng-if? I want it to work inside ng-if.. Is there any solution???
