### ISSUE TITLE
Required when using as a form input

### ISSUE THREAD

**Issue by gruberb** [sachinchoolur/angular-trix#5]
When using angular-trix as an input for a from, I want to be able to put a required attribute so I can use the build-in form validation from HTML5 browsers.

Any idea how to implement this? I am happy to do it, but I cannot think of a neat and simple solution right now (checking if the ng-model is set could be a solution before submitting, but this seams not very solid.)

**Comment by hcientist** [comment]
perhaps a temporary workaround for you would be to add a hidden input item that is also bound to the sam model as your editor and make that required?
